buggy/post/views.py
# -*- coding: utf8 -*-
"""Post views module."""
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from sqlalchemy.orm import joinedload

from buggy.comment.forms import CreateCommentForm
from buggy.database import db
from buggy.settings import Config
from buggy.utils import admin_user_required, flash_errors, get_or_create

from .forms import CreatePostForm
from .models import Post, Tag
from .utils import tags_by_data

blueprint = Blueprint('posts', __name__, static_folder='../static')


@blueprint.route('/', defaults={'page': 1})
@blueprint.route('/<page>')
def home(page):
    """Posts view."""
    posts = Post.query.options(joinedload('related_tags')).order_by(
        Post.created_at.desc()
    )
    paginator = posts.paginate(int(page), per_page=Config.POSTS_PER_PAGE)
    return render_template(
        'posts/home.html', posts=paginator.items, paginator=paginator
    )


@blueprint.route('/tag/<tag>', defaults={'page': 1})
@blueprint.route('/tag/<tag>/<page>')
def get_post_by_tag(tag, page):
    posts = Post.query.filter(Post.related_tags.any(name=tag))
    paginator = posts.paginate(int(page), per_page=Config.POSTS_PER_PAGE)

    # Paginator renderer uses url_for to generete paginator.
    # So we need somehow render urls with /tag/page
    kwargs = {'tag': tag}

    return render_template(
        'posts/home.html', posts=paginator.items, paginator=paginator,
        paginator_kwargs=kwargs
    )


@blueprint.route('/post/<slug>', methods=['GET'])
def post_detail(slug):
    """Post detail view."""
    form = CreateCommentForm(request.form)

    post = Post.query.options(
        joinedload('comments')
    ).filter_by(slug=slug).first()

    if not post:
        abort(404)

    return render_template('posts/detail.html', post=post, form=form)


@blueprint.route('/create_post/', methods=['GET', 'POST'])
@login_required
@admin_user_required
def create_post():
    """Create post with tags view."""
    form = CreatePostForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(
                title=form.title.data,
                raw_content=form.content.data,
                user_id=current_user.id,
                slug=Post.make_slug(form.title.data)
            )

            # Generate the TAGS!
            if form.tags.data:
                tags_to_add = tags_by_data(form.tags.data)
                for tag in tags_to_add:
                    post.related_tags.append(tag)

            # Create by single request post with tags.
            db.session.add(post)
            db.session.commit()

            flash('Post successfully added.', 'success')
            return redirect(url_for('posts.home'))
        else:
            flash_errors(form, 'danger')
    return render_template('posts/create_post.html', form=form)


@blueprint.route('/edit_post/<slug>', methods=['GET', 'POST'])
@login_required
@admin_user_required
def edit_post(slug):
    """
    Here we updating post, and performing minimal database action
    to create/delete new tags.
    Need to refactor tags create/delete functionality.
    """

    # Post must exist.
    post = Post.query.options(
        joinedload('related_tags')).filter_by(slug=slug).first()

    if not post:
        abort(404)

    related_tags = post.related_tags

    # Updating post on POST request.
    if request.method == 'POST':
        form = CreatePostForm(request.form)

        if form.validate_on_submit():
            # Prepare to update
            post.update(
                title=form.title.data,
                raw_content=form.content.data,
                user_id=current_user.id,
                commit=False
            )

            # Tags stuff
            old_tags_dict = {str(tag): tag for tag in related_tags}
            old_tags = set(old_tags_dict.keys())

            input_tags = set(map(str.strip, form.tags.data.split(',')))
            input_tags.discard('')

            if input_tags != old_tags:
                common = old_tags & input_tags
                to_delete = old_tags - common
                to_add = input_tags - common

                # Perform addition
                for tag_name in to_add:
                    obj, _ = get_or_create(Tag, name=tag_name)
                    post.related_tags.append(obj)

                # Perform deletion
                for tag_str in to_delete:
                    post.related_tags.remove(old_tags_dict[tag_str])

            db.session.commit()
            flash('Post {slug} was updated'.format(slug=post.slug), 'success')
        else:
            flash_errors(form, 'danger')

    # GET
    else:
        # Render form with existing info.
        tags = ', '.join(str(tag) for tag in related_tags)

        form = CreatePostForm(obj=post)
        form.tags.data = tags

    # Finally, render form.
    return render_template(
        'posts/edit_post.html',
        form=form,
        post=post,
    )

buggy/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user

from buggy.extensions import login_manager
from buggy.utils import flash_errors

from .forms import LoginForm, RegisterForm
from .models import User

blueprint = Blueprint('user', __name__, static_folder='../static')


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route('/login/', methods=['GET', 'POST'])
def login():
    """Login page"""
    form = LoginForm(request.form)
    # Handle logging in
    if request.method == 'POST':
        print(form.user)
        if form.validate_on_submit():
            login_user(form.user)
            flash('You are logged in.', 'success')
            redirect_url = request.args.get('next') or url_for('posts.home')
            return redirect(redirect_url)
        else:
            flash_errors(form, 'danger')
    return render_template('users/login.html', form=form)


@blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    """Register page"""
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            User.create(
                username=form.username.data,
                email=form.email.data,
                password=form.password.data,
                is_active=True
            )
            flash('You successfully registered. Please log in.', 'success')
            return redirect(url_for('user.login'))
        else:
            flash_errors(form, 'danger')
    return render_template('users/register.html', form=form)


@blueprint.route('/logout/')
@login_required
def logout():
    """Logout."""
    logout_user()
    flash('You are logged out.', 'info')
    return redirect(url_for('posts.home'))

buggy/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
Unauthorized
{% endblock %}

buggy/templates/footer.html
<footer class="blog-footer">
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

buggy/templates/layout.html
{% macro render_pagination(pagination, endpoint, kwargs) %}
  <div class=pagination>
  <ul class="pagination">
  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li><a href="{{ url_for(endpoint, page=page, **kwargs) }}"> {{ page }}</a></li>
      {% else %}
        <li class="active"><a>{{ page }}</a></li>
      {% endif %}
    {% else %}
      <li><a><span class=ellipsis>…</span></a></li>
    {% endif %}
  {%- endfor %}
  </ul>
  </div>
{% endmacro %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="icon" href="../../favicon.ico">
  <title>
    {% block page_title %}
    Buggy blog
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">
  {% assets "css_all" %}
  <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}
  <script type="text/javascript" async src="/static/libs/MathJax/MathJax.js?config=TeX-AMS_HTML"></script>
  {% block js %}
  {% endblock %}
</head>
<body>
{% block body %}
{% include 'navbar.html' %}
<div class="container">
  <div class="blog-header">
    <h1 class="blog-title">Buggy blog</h1>
    <p class="lead blog-description">Test flask-based blog.</p>
  </div>
  <div class="row">
    <div class="col-sm-8 blog-main">
      {% include 'messages.html' %}
      {% block content %}{% endblock %}
    </div><!-- /.blog-main -->
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    {% include 'sidebar.html' %}
    </div>
  </div><!-- /.row -->
</div><!-- /.container -->
{% include 'footer.html' %}
{% endblock %}
{% if ENABLE_DISQUS %}
<script id="dsq-count-scr" src="//{{ DISQUS_SHORTNAME }}.disqus.com/count.js" async></script>
{% endif %}
</body>
</html>

buggy/templates/messages.html
<div role="main">
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  <div class="row">
    <div class="col-md-12">
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{message}}
      </div><!-- end .alert -->
      {% endfor %}
    </div><!-- end col-md -->
  </div><!-- end row -->
  {% endif %}
  {% endwith %}
</div>

buggy/templates/navbar.html
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav">
      <a class="blog-nav-item {%- if request.path == '/' %} active {% endif %}"
         href="{{ url_for('posts.home') }}">Home</a>
      {% if current_user and current_user.is_authenticated %}
      {% if current_user.is_admin %}
        <a class="blog-nav-item {%- if request.path == '/create_post/' %} active {% endif %}"
           href="{{ url_for('posts.create_post') }}">Create post</a>
      {% endif %}
      <a class="blog-nav-item">Welcome, <strong>{{current_user.username}}</strong>.</a>
      <a class="blog-nav-item" href="{{ url_for('user.logout') }}">Logout</a>
      {% else %}
      <a class="blog-nav-item {%- if request.path == '/login/' %} active {% endif %}"
         href="{{ url_for('user.login') }}">Sign In</a>
      <a class="blog-nav-item {%- if request.path == '/register/' %} active {% endif %}"
         href="{{ url_for('user.register') }}">Sign Up</a>
      {% endif %}
    </nav>
  </div>
</div>

buggy/templates/sidebar.html
<div class="sidebar-module sidebar-module-inset">
  <h4>About</h4>
  <p>We can write crapcode for you.</p>
</div>
<div class="sidebar-module sidebar-module-inset">
  <h4>Top-15 tags</h4>
  {% for tag, posts in tags %}
  <a class="related_tag" href="/tag/{{tag}}" title="posts: {{posts}}">{{tag}}</a>
  {% endfor %}
</div>
<div class="sidebar-module">
  <h4>Archives</h4>
  <ol class="list-unstyled">
    <li><a href="#">March 2014</a></li>
    <li><a href="#">February 2014</a></li>
    <li><a href="#">January 2014</a></li>
    <li><a href="#">December 2013</a></li>
    <li><a href="#">November 2013</a></li>
    <li><a href="#">October 2013</a></li>
    <li><a href="#">September 2013</a></li>
    <li><a href="#">August 2013</a></li>
    <li><a href="#">July 2013</a></li>
    <li><a href="#">June 2013</a></li>
    <li><a href="#">May 2013</a></li>
    <li><a href="#">April 2013</a></li>
  </ol>
</div>
<div class="sidebar-module">
  <h4>Elsewhere</h4>
  <ol class="list-unstyled">
    <li><a href="#">GitHub</a></li>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">Facebook</a></li>
  </ol>
</div>