buggy/post/models.py
# -*- coding: utf-8 -*-
"""User models"""

import datetime as dt

from flask import Markup
from slugify import UniqueSlugify

from buggy.database import (Column, Model, SurrogatePK, db, reference_col,
                            relationship)

# ManyToMany stuff
tags_association_table = db.Table(
    'association',
    Model.metadata,
    Column('posts_pk', db.Integer, db.ForeignKey('posts.id')),
    Column('tags_pk', db.Integer, db.ForeignKey('tags.name'))
)


class Post(SurrogatePK, Model):
    """Posts model"""

    __tablename__ = 'posts'
    title = Column(db.String(200), nullable=False)
    created_at = Column(
        db.DateTime, nullable=False, default=dt.datetime.utcnow
    )
    raw_content = Column(db.Text(), nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='posts')
    related_tags = relationship(
        'Tag',
        secondary=tags_association_table,
        back_populates='related_posts',
    )
    slug = Column(
        db.String(50), nullable=True, unique=True
    )

    def __init__(self, title, **kwargs):
        """Forces to create instance with specific arguments."""
        db.Model.__init__(self, title=title, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Post({title})>'.format(title=self.title)

    @property
    def content(self):
        return Markup(self.raw_content)

    @property
    def cute_date(self):
        """Date cutifier."""
        return self.created_at.strftime('Created %d, %b %Y')

    @classmethod
    def unique_post_slug_checker(cls, text, uids):
        """
        Checks if slug already exists.
        Used in slugify.UniqueSlug from awesome-slugify.
        """
        if text in uids:
            return False
        return not Post.query.filter(Post.slug == text).first()

    @classmethod
    def make_slug(cls, title):
        """
        Redefined to create unique post slug from title.
        """
        slugify_title = UniqueSlugify(
            unique_check=Post.unique_post_slug_checker,
            to_lower=True,
            max_length=50
        )
        return slugify_title(title)


class Tag(Model):
    """Post tags model"""

    __tablename__ = 'tags'
    name = Column(db.String(100), primary_key=True)
    related_posts = relationship(
        'Post',
        secondary=tags_association_table,
        back_populates='related_tags',
    )

    def __str__(self):
        return self.name

    def __repr__(self):
        return '<Tag({name})>'.format(name=self.name)

    @classmethod
    def clean_unattached_tags(cls):
        """Cleans all tags, that are not attached to any post."""
        tags = cls.query.all()
        for tag in tags:
            if not tag.related_posts:
                tag.delete()

buggy/post/forms.py
# -*- coding: utf-8 -*-
"""Post forms."""
from flask_wtf import Form
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length


class CreatePostForm(Form):
    """Create post form"""

    title = StringField('Title', validators=[DataRequired(), Length(max=250)])
    content = TextAreaField('Content', validators=[DataRequired(),
                                                   Length(max=50000)])
    tags = StringField('Tags', validators=[Length(max=1000)])

buggy/comment/views.py
# -*- coding: utf8 -*-
"""Comment views."""
from flask import Blueprint, flash, redirect, request, url_for

from buggy.utils import flash_errors

from .forms import CreateCommentForm
from .models import Comment

blueprint = Blueprint('comments', __name__, static_folder='../static')


@blueprint.route('/post/<slug>/create_comment', methods=['POST'])
def create_comment(slug):
    form = CreateCommentForm(request.form)
    if form.validate_on_submit():
        Comment.create(
            name=form.name.data,
            email=form.email.data,
            text=form.text.data,
            post_id=int(form.post_id.data)
        )
        flash('Comment added.', 'success')
    else:
        flash_errors(form, 'danger')
    return redirect(url_for('posts.post_detail', slug=slug))

buggy/post/__init__.py
# -*- coding: utf-8 -*-
"""Post module."""
from . import views  # noqa

buggy/post/views.py
# -*- coding: utf8 -*-
"""Post views module."""
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from sqlalchemy.orm import joinedload

from buggy.comment.forms import CreateCommentForm
from buggy.database import db
from buggy.settings import Config
from buggy.utils import admin_user_required, flash_errors, get_or_create

from .forms import CreatePostForm
from .models import Post, Tag
from .utils import tags_by_data

blueprint = Blueprint('posts', __name__, static_folder='../static')


@blueprint.route('/', defaults={'page': 1})
@blueprint.route('/<page>')
def home(page):
    """Posts view."""
    posts = Post.query.options(joinedload('related_tags')).order_by(
        Post.created_at.desc()
    )
    paginator = posts.paginate(int(page), per_page=Config.POSTS_PER_PAGE)
    return render_template(
        'posts/home.html', posts=paginator.items, paginator=paginator
    )


@blueprint.route('/tag/<tag>', defaults={'page': 1})
@blueprint.route('/tag/<tag>/<page>')
def get_post_by_tag(tag, page):
    posts = Post.query.filter(Post.related_tags.any(name=tag))
    paginator = posts.paginate(int(page), per_page=Config.POSTS_PER_PAGE)

    # Paginator renderer uses url_for to generete paginator.
    # So we need somehow render urls with /tag/page
    kwargs = {'tag': tag}

    return render_template(
        'posts/home.html', posts=paginator.items, paginator=paginator,
        paginator_kwargs=kwargs
    )


@blueprint.route('/post/<slug>', methods=['GET'])
def post_detail(slug):
    """Post detail view."""
    form = CreateCommentForm(request.form)

    post = Post.query.options(
        joinedload('comments')
    ).filter_by(slug=slug).first()

    if not post:
        abort(404)

    return render_template('posts/detail.html', post=post, form=form)


@blueprint.route('/create_post/', methods=['GET', 'POST'])
@login_required
@admin_user_required
def create_post():
    """Create post with tags view."""
    form = CreatePostForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(
                title=form.title.data,
                raw_content=form.content.data,
                user_id=current_user.id,
                slug=Post.make_slug(form.title.data)
            )

            # Generate the TAGS!
            if form.tags.data:
                tags_to_add = tags_by_data(form.tags.data)
                for tag in tags_to_add:
                    post.related_tags.append(tag)

            # Create by single request post with tags.
            db.session.add(post)
            db.session.commit()

            flash('Post successfully added.', 'success')
            return redirect(url_for('posts.home'))
        else:
            flash_errors(form, 'danger')
    return render_template('posts/create_post.html', form=form)


@blueprint.route('/edit_post/<slug>', methods=['GET', 'POST'])
@login_required
@admin_user_required
def edit_post(slug):
    """
    Here we updating post, and performing minimal database action
    to create/delete new tags.
    Need to refactor tags create/delete functionality.
    """

    # Post must exist.
    post = Post.query.options(
        joinedload('related_tags')).filter_by(slug=slug).first()

    if not post:
        abort(404)

    related_tags = post.related_tags

    # Updating post on POST request.
    if request.method == 'POST':
        form = CreatePostForm(request.form)

        if form.validate_on_submit():
            # Prepare to update
            post.update(
                title=form.title.data,
                raw_content=form.content.data,
                user_id=current_user.id,
                commit=False
            )

            # Tags stuff
            old_tags_dict = {str(tag): tag for tag in related_tags}
            old_tags = set(old_tags_dict.keys())

            input_tags = set(map(str.strip, form.tags.data.split(',')))
            input_tags.discard('')

            if input_tags != old_tags:
                common = old_tags & input_tags
                to_delete = old_tags - common
                to_add = input_tags - common

                # Perform addition
                for tag_name in to_add:
                    obj, _ = get_or_create(Tag, name=tag_name)
                    post.related_tags.append(obj)

                # Perform deletion
                for tag_str in to_delete:
                    post.related_tags.remove(old_tags_dict[tag_str])

            db.session.commit()
            flash('Post {slug} was updated'.format(slug=post.slug), 'success')
        else:
            flash_errors(form, 'danger')

    # GET
    else:
        # Render form with existing info.
        tags = ', '.join(str(tag) for tag in related_tags)

        form = CreatePostForm(obj=post)
        form.tags.data = tags

    # Finally, render form.
    return render_template(
        'posts/edit_post.html',
        form=form,
        post=post,
    )

buggy/templates/posts/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="container-narrow">
  <h1>Create post</h1>
  <br/>
  <form id="registerForm" class="form form-register" method="POST" action="{{ url_for('posts.create_post') }}" role="form">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="form-group">
      {{form.title.label}}
      {{form.title(placeholder="Title", class_="form-control")}}
    </div>
    <div class="form-group">
      {{form.content.label}}
      {{form.content(placeholder="Content", class_="form-control", rows=10)}}
    </div>
    <div class="form-group">
      {{form.tags.label}}
      {{form.tags(placeholder="Tags", class_="form-control")}}
    </div>
    <p><input class="btn btn-default btn-submit" type="submit" value="Create post"></p>
  </form>
</div>
{% endblock %}

buggy/templates/posts/detail.html
{% extends "layout.html" %}
{% block content %}
  <div class="blog-post">
    <h2 class="blog-post-title">
      {{ post.title }}
    </h2>
    <p class="blog-post-meta">{{ post.cute_date }} by <a href="#">{{ post.user.username }}</a></p>
    <p>
      {{ post.content }}
    </p>
    <span class="related_tags">
    {% if post.related_tags %}
      <i class="fa fa-tags tag-icon" aria-hidden="true"></i>
    {% endif %}
      {% for tag in post.related_tags %}
        <a class="related_tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
      {% endfor %}
        </span>
  </div><!-- end blog-post -->

  <div class="tex2jax_ignore">
  {% if ENABLE_DISQUS %}
    <div id="disqus_thread"></div>
    <script>
      var disqus_config = function () {
        this.page.url = "{{ request.url }}";
        this.page.identifier = "{{ post.slug }}";
      };
      (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://{{ DISQUS_SHORTNAME }}.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
      })();
    </script>
    <noscript>Please enable JavaScript to view the comments.</noscript>
  {% else %}
    <hr>
    <h4 class="text-center">Leave a Comment:</h4>
    <form id="registerForm" class="form form-register" method="POST" action="{{ url_for('comments.create_comment', slug=post.slug) }}" role="form">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <input type="hidden" name="post_id" value="{{ post.id }}"/>
      <div class="form-group">
        {{form.name.label}}
        {{form.name(placeholder="Name", class_="form-control")}}
      </div>
      <div class="form-group">
        {{form.email.label}}
        {{form.email(placeholder="Email", class_="form-control")}}
      </div>
      <div class="form-group">
        {{form.text.label}}
        {{form.text(placeholder="Text", class_="form-control")}}
      </div>
      <p><input class="btn btn-default btn-submit" type="submit" value="Comment"></p>
    </form>
    {% for comment in post.comments %}
      <hr>
      <!-- Comment -->
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">{{ comment.name }}
            <small>{{ comment.cute_date }}</small>
          </h4>
          {{ comment.text }}
        </div>
      </div>
    {% endfor %}
    <hr>
  {% endif %}
  </div>
{% endblock %}

buggy/templates/posts/edit_post.html
{% extends "layout.html" %}
{% block js %}
    <script type="text/javascript" src="/static/libs/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'#post_edit' });</script>
{% endblock %}
{% block content %}
<div class="container-narrow">
  <h1>Edit post</h1>
  <br/>
  <form id="registerForm" class="form form-register" method="POST" action="{{ url_for('posts.edit_post', slug=post.slug) }}" role="form">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="form-group">
      {{form.title.label}}
      {{form.title(placeholder="Title", class_="form-control")}}
    </div>
    <div class="form-group">
      {{form.content.label}}
      {{form.content(placeholder="Content", class_="form-control", rows=10, id="post_edit")}}
    </div>
    <div class="form-group">
      {{form.tags.label}}
      {{form.tags(placeholder="Tags", class_="form-control")}}
    </div>
    <p><input class="btn btn-default btn-submit" type="submit" value="Update post"></p>
  </form>
</div>
{% endblock %}

buggy/templates/posts/home.html
{% extends "layout.html" %}
{% block content %}
<div class="blog-post">
  {% for post in posts %}
  <h2 class="blog-post-title">
    <a class="blog-post-title-href" href="{{url_for('posts.post_detail', slug=post.slug)}}">{{post.title}}</a>
  </h2>
  <p class="blog-post-meta">
      {{post.cute_date}} by {{post.user.username}}
      {% if current_user.is_admin %}
      <a href="{{ url_for('posts.edit_post', slug=post.slug) }}">edit</a>
      {% endif %}
  </p>
  <p>
    {{post.content}}
  </p>
  <span class="related_tags">
    {% if post.related_tags %}
    <i class="fa fa-tags tag-icon" aria-hidden="true"></i>
    {% endif %}
    {% for tag in post.related_tags %}
    <a class="related_tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
    {% if ENABLE_DISQUS %}
    <p>
        <a
          href="{{url_for('posts.post_detail', slug=post.slug)}}#disqus_thread"
          data-disqus-identifier="{{ post.slug }}"
          class="comments-counter"
        >
        </a>
    </p>
    {% endif %}
    {% endfor %}
  </span>
  <hr>
  {% else %}
  <p>No posts yet.</p>
  {% endfor %}
</div><!-- end blog-post -->
    {% if paginator.pages > 1 %}
      {{ render_pagination(paginator, 'posts.home', paginator_kwargs) }}
    {% endif %}
{% endblock %}